In [38]:
def prime_number_or_not(a):
    c=0
    for i in range(1,a+1):
        if(a%i==0):
            c=c+1
    if(c==2):
        print("prime")
    else:
        print("not prime")
            
                        
        

In [42]:
prim_range(lb,ub)
def prim_range(lb,ub):
    for i in range (1,ub+1):
        if prime_number_or_not(a):
            print(a)
    
     
        

prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime
prime


In [45]:
def primes(n):
    if n<2:
        print("not a prime")
    for i in range(2,n//2):
        if n%i==0:
            return False
        return True
if primes(143):
    print("is prime")
else:
    print("is not a prime")
    

is prime


In [10]:
def fac_count(a):
    c=0
    for i in range(1,a+1):
        if(a%i==0):
            c=c+1
    return c

In [11]:
def isprime(a):
    fc=fac_count(a)
    if fc==2:
        return True
    return False

In [12]:
i=int(input())
if isprime(i):
    print("is prime")
else:
    print("not prime")


7
is prime


In [13]:
l=list(map(int,['1','2','3','4']))
print(l)

[1, 2, 3, 4]


In [14]:
l=['1','2','3','4']
l1=[]
for i in l:
    j=int(i)
    l1.append(j)
print(l1)
    

[1, 2, 3, 4]


In [16]:
list(map(int,l))

[1, 2, 3, 4]

In [17]:
list(map(str,l))

['1', '2', '3', '4']

In [18]:
i=input()

program


In [19]:
i

'program'

In [20]:
i=input().split()

python program


In [21]:
i

['python', 'program']

In [ ]:
list(map(str,input().split()))

In [2]:
dir(str)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',


In [3]:
def addition(n):
    return n+n+n


In [4]:
list(map(addition,[4,8,9,5,6]))

[12, 24, 27, 15, 18]

In [5]:
def subtraction(n):
    return n-2

In [6]:
list(map(subtraction,[9,8,7,6,5]))

[7, 6, 5, 4, 3]

def

In [7]:
def power(n):
    return n**n
l=list(map(power,[9,8,5,4]))
for i in l:
    print(i)

387420489
16777216
3125
256


# filters

In [8]:
li=[1,2,'a','b','c',3]
def isdigit(n):
    n=str(n)
    if n.isdigit():
        return True
    return False
list(filter(isdigit,li))

[1, 2, 3]

In [56]:
l=[1,2,3,4,5,6,7,8,9]
def primes(n):
    if n<2:
        return True
    for i in range(2,n//2+1):
        if n%i==0:
            return False
    return True
def even(n):
    if n%2==0:
        return True
    return False
def odd(n):
    if n%2!=0:
        return True
    return False
print(list(filter(primes,l)))
print(list(filter(even,l)))
print(list(filter(odd,l)))

[1, 2, 3, 5, 7]
[2, 4, 6, 8]
[1, 3, 5, 7, 9]


In [53]:
l=[1,2,3,4,5,6,7,8,9]
def primes(n):
     c=0
for i in range(1,n+1):
        if(n%i==0):
            c=c+1
        if(c==2):
        return True
    return False
          
def even(n):
    if n%2==0:
        return True
    return False
def odd(n):
    if n%2!=0:
        return True
    return False
print(list(filter(primes,l)))
print(list(filter(even,l)))
print(list(filter(odd,l)))

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 9)

# lambdas

In [1]:
h = lambda x : x%2==0
list(filter(h,[1,2,3,4,5]))

[2, 4]

In [4]:
l = [1,2,3,4,5,6,7,8,9,10]
o=lambda i:i%2!=0
list(filter(o,l))

[1, 3, 5, 7, 9]

In [10]:
print[r(1,25) for i in range(1,11)]

SyntaxError: invalid syntax (<ipython-input-10-e5edfc981ef2>, line 1)

In [13]:
from random import randint as r
for i in range (1,10+1):
    print(r(1,25))

24
5
17
19
16
21
14
21
8
12


In [14]:
m1=[r(1,45) for i in range (1,11)]
m2=[r(1,45) for i in range (1,11)]
m3=[r(1,45) for i in range (1,11)]
print(m1)
print(m2)
print(m3)

[15, 11, 40, 21, 16, 44, 26, 30, 9, 15]
[23, 9, 19, 31, 15, 34, 12, 29, 1, 30]
[36, 28, 29, 33, 2, 44, 23, 36, 17, 28]


In [19]:
a1= list(map(lambda x,y,z:(x+y+z)//3,m1,m2,m3))
print(a1)

[24, 16, 29, 28, 11, 40, 20, 31, 9, 24]


In [21]:
a2= list(map(lambda x,y:(x+y)/2,m1,m2))
print(a2)

[19.0, 10.0, 29.5, 26.0, 15.5, 39.0, 19.0, 29.5, 5.0, 22.5]


In [24]:
a4=list(filter(lambda x:x<10,a2))
print(a4)

[5.0]


In [28]:
a5=list(filter(lambda x:x>10,m1))
print(a5)

[15, 11, 40, 21, 16, 44, 26, 30, 15]


# numPY

In [29]:
import numpy as np

In [30]:
l=[1,2,3,4,5]
a1=np.array(l)
print(a1)

[1 2 3 4 5]


In [33]:
l1=[[1,2,3,4,5],[1,2,3,4,5]]
a2=np.array(l1)
print(a2)

[[1 2 3 4 5]
 [1 2 3 4 5]]


In [34]:
l3=[[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]]
a3=np.array(l3)
print(a3)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


In [37]:
a=np.arange(5).reshape(5,1)
print(a)

[[0]
 [1]
 [2]
 [3]
 [4]]


In [38]:
a1=np.arange(100).reshape(5,20)
print(a1)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]


In [40]:
b=np.arange(20,30).reshape(5,2)
c=np.arange(20,30).reshape(2,5)
print(b)
print(c)

[[20 21]
 [22 23]
 [24 25]
 [26 27]
 [28 29]]
[[20 21 22 23 24]
 [25 26 27 28 29]]


In [47]:
d=np.arange(0,6).reshape(2,3)
e=np.arange(1,7).reshape(2,3)
f=np.arange(2,8).reshape(1,6)
g=np.arange(3,9).reshape(6,1)
print(d)
print(g)
print(f)
print(e)

[[0 1 2]
 [3 4 5]]
[[3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[2 3 4 5 6 7]]
[[1 2 3]
 [4 5 6]]


In [48]:
d+e

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [49]:
d-e

array([[-1, -1, -1],
       [-1, -1, -1]])

In [50]:
d/2

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5]])

In [51]:
d*e

array([[ 0,  2,  6],
       [12, 20, 30]])

In [53]:
d//e

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [56]:
print(sqrt(e))

NameError: name 'sqrt' is not defined

In [57]:
print(np.sin(d))

[[ 0.          0.84147098  0.90929743]
 [ 0.14112001 -0.7568025  -0.95892427]]


In [58]:
print(np.shape(d))

(2, 3)


In [60]:
d.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [61]:
d[::-1]

array([[3, 4, 5],
       [0, 1, 2]])